reviews:
  base_branches: ["dev"]
  profile: chill
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
