name: Coderabbit Code Review (na dev)

on:
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read
  pull-requests: write

jobs:
  coderabbit_review:
    runs-on: ubuntu-latest
    name: Coderabbit AI Review
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Spustit Coderabbit AI Review
        uses: Coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
